### ISSUE TITLE
checks not working for Bitbucket scm

### ISSUE THREAD

**Issue by vijay-jangir** [jenkinsci/checks-api-plugin#249] opened 2024-03-06 18:00 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

rhel 8

### Reproduction steps

running recordCoverage using Bitbucket as scm gives error

[Checks API] No suitable checks publisher found.

### Expected Results

coverage should be published to bitbucket code insights

### Actual Results

[Checks API] No suitable checks publisher found.

### Are you interested in contributing a fix?

Sure, with some guidance i can contribute to code, i can test it for integration with Bitbucket

**Comment by timja** [comment] 2024-03-06 21:52
Duplicate of https://github.com/jenkinsci/checks-api-plugin/issues/65

**Closed by timja** 2024-03-06 21:52 UTC
